### ISSUE TITLE
Add vehicle camber, trackWidth and wheel height setters

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1197]
### Description of the problem

Natives don't give ability to set those, but it can be set manually in the memory. It can be a nice feature to the alt:V, since i haven't seen those setters on other multiplayer platforms

### Desired solution for the problem

https://github.com/E66666666/GTAVStancer/blob/master/SlamIt/script.cpp#L94

**Comment by zziger** [comment]
Practical use case: Some vehicle have mods with wide fenders, and it would look much better if there would be an ability to set trackWidth, so wheels would be wider 
![image](https://user-images.githubusercontent.com/27638710/139971087-830236b6-416d-4eb3-9257-c5e2b663aa72.png)

**Comment by MARIO228** [comment]
We would like to see Stancer or such functions to be on Alt:V, since we are interested in that on our server! :)
Such thing you can see in Forza Horizon 5, where you can change at least vehicle width, but this was mentioned [here](https://github.com/altmp/altv-issues/issues/385) before. Hope to see that in the future!

**Comment by C0kkie** [comment]
Added in next update
