### ISSUE TITLE
OnCreateBaseObject being called on non existent entities

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1424]
### Description of the problem

If you have a vehicle, then restart a server and reconnect - OnCreateBaseObject will be called for the vehicle that doesn't exist already

### Reproduction steps

1. Spawn a vehicle
2. Restart server
3. Reconnect
4. You received a OnCreateBaseObject, if you will spawn a new one - you will receive OnCreateBaseObject for object with the same id

### Expected behaviour

Not receiving OnCreateBaseObject for objects that don't exist already

### Operating system

Windows

### Version

dev 10.x

**Comment by zziger** [comment]
Found the bug in clientside C# module, and reproduced in clientside JS too

**Comment by LeonMrBonnie** [comment]
> > Unsure if it's actually a bug.
> 
> Well basically you receive OnCreateBaseObject for entity that doesn't exist, idk if that would be the intended behavior

What do you mean it doesn't exist? You mean it doesn't exist in the game world? When yes, that is still the correct behaviour, because the create base object event is for the creation of base objects (the actual object instance, not the game object)
So it's related to alt:V's entity system not the GTA V entity system.

**Comment by C0kkie** [comment]
Fixed in dev/11.0-dev35
