### ISSUE TITLE
Ability to use ASI mods

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1538]
### Description of the problem

I'm using Rockstar Editor besides mods like `openCameraV.asi` and `ExtendedVideoExport.asi` every day which only works with `dinput8.dll` (Script Hook V).
When Rockstar released a new update `dinput8.dll` doesn't work until the developers of `Script Hook V` updated to the new version.
This update takes a long time, for example, 10 days or more.
This option can be disabled by server developers in `server.cfg` to prevent cheating.

### Additional context

`openCameraV.asi` https://openiv.com/?p=1160
`ExtendedVideoExport.asi` https://www.gta5-mods.com/scripts/extended-video-export
`Script Hook V` https://www.dev-c.com/gtav/scripthookv/

**Comment by FabianTerhorst** [comment]
We won't allow scripthook.

**Comment by FabianTerhorst** [comment]
Feel free to post the source of the asi mods so that they could be natively integrated.

**Comment by MARIO228** [comment]
> Feel free to post the source of the asi mods so that they could be natively integrated.

May be this one - https://www.gta5-mods.com/scripts/extended-video-export, as he mentioned in his post, that gives creators to export video with good quality, with codec that they want. But it doesn't work in FiveM atm (worked before), but works with SP. 

But this one (i uploaded it to my mega account, because i didn't find a github link or anything, it was shared by one of our community members and we use it, i can upload it differently, if needed) - https://mega.nz/file/rMs0DbhA#jjxCNHaAkO4OIdogG65tkafozA1cGSHQU6TW8vNZ6NA 
![image](https://user-images.githubusercontent.com/40245545/177307231-1019a777-9f47-4056-89e4-23bf7b7d66cd.png)


Works with FiveM atm, but it looks similar to Extended Video Export -> EVE, but called Simple Video Export, which can be placed in "plugins" folder there and it works, compare to EVE, that needs to be placed in like "cache -> subprocess" folder to make it working back in the days)
