### ISSUE TITLE
Objects don't spawn in different parts of the map

### ISSUE THREAD

**Issue by Serske** [altmp/altv-issues#1751]
### Description of the problem

Objects don't spawn in different parts of the map
```
Tested objects:
v_corp_bk_chair2
v_corp_cd_recseat
v_corp_desksetb
v_corp_servrtwrfd
v_ind_meatbox
v_serv_ct_chair01
And etc
```
No object spawns in this pos: **new alt.Vector3(1822.142, 2033.965, 75.351)**
All objects spawns in this pos **new alt.Vector3(263.389, -919.577, 29.088)**

### Reproduction steps

```
const player = alt.Player.local;
const object = new alt.Object(alt.hash("v_corp_bk_chair2"), player.pos, player.rot);
 ```

### Expected behaviour

Object will spawn in any part of map

### Operating system

Windows 10 21H1

### Version

release/13.40

### Reproduction tested

- [ ] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by LeonMrBonnie** [comment]
Some objects require a YTYP to be loaded before, that is the same behaviour for natives as well.

(Also small sidenote; The checkbox that you tested on dev **is there for a reason**. Check it again just to post the issue and then uncheck it afterwards because you didn't actually test on dev and you will be banned from posting further issues.)
