### ISSUE TITLE
Invisible players after spawn

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1979]
### Description of the problem

Remote players are invisible right after spawn, ~~caused by workaround for #1046~~

![изображение](https://github.com/altmp/altv-issues/assets/54737754/b421d25e-33e0-4ca7-b626-8ec3b6d6d451)

### Reproduction steps

1. Add spawn of player in playerConnect event listener
1. Connect first player to server
2. Connect second player to server
3. First player is invisible for second player

### Expected behaviour

/

### Operating system

Windows 11

### Version

15.0-dev589

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by martonp96** [comment]
Not related to altv directly

**Comment by litolax** [comment]
Confirmed with the latest dev (722)

```js
player.spawn(0,0, 75);
player.model = "mp_m_freemode_01";
player.dimension = 0;

alt.Player.all[1].spawn(0,0,75);
alt.Player.all[1].model = "mp_m_freemode_01";
alt.Player.all[1].dimension = 0;
```

**Comment by MyHwu9508** [comment]
The issue improved a bit since the last alt:V dev branch update [8faa88f](https://github.com/altmp/altv/commit/8faa88fc4daaf22ed42e1da035d8e0f11c9c922f) - Player model change fix

However now the model changes properly, but directly after the model change we also apply ped decorations and clothing. For the player itself everything is correctly applied. Players in streaming range need to restream the player, otherwise they just see the plain model.

**Comment by xxshady** [comment]
Fixed in next dev
