### ISSUE TITLE
Animal-peds bugged after using player skin methods

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#2088]
### Description of the problem

![image](https://github.com/altmp/altv-issues/assets/17340739/53026be8-34b6-43c0-9881-c9be8f36efa9)

If u spawn as mp_m_freemode_01 and then set on of these:

HeadBlendData
EyeColor
HairColor
HairHighlightColor
FaceFeature
HeadOverlay

Its buged like in the Screenshot

### Reproduction steps

```
player.spawn(0,0,72)
player.model = "mp_m_freemode_01"
player.setHairHighlightColor(0);
player.model = alt.hash("a_c_panther")
```

### Expected behaviour

Ped is normally set

![image](https://github.com/altmp/altv-issues/assets/17340739/eb6693e0-89e3-4c23-9b64-7d790d7eb657)

### Operating system

Windows 11

### Version

15.19 (release) & 15.0-dev810 (dev)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Confirmed on 15.0-dev810

**Comment by FabianTerhorst** [comment]
you need to remove head blend data after calling hair highlight color manually.

**Comment by FabianTerhorst** [comment]
face feature also has a remove method already.

**Comment by FabianTerhorst** [comment]
head overlay has a remove method as well. eye color and hair color needs head blend data remove.

**Comment by xxshady** [comment]
> face feature also has a remove method already.

@FabianTerhorst and it doesn't work

**Comment by FabianTerhorst** [comment]
> > face feature also has a remove method already.
> 
> @FabianTerhorst and it doesn't work: #1919

that one only works when you call it right before model change

**Comment by chdxD1** [comment]
from a discussion with @Doxoh my stance on the topic is: We can't know when removing the HeadBlendData or resetting HairHighlightColor has passed sync onto the client. Requiring a 100ms delay (which might be too much or too less depending on sync speed?) before changing the model is basically gambling on the sync. IMHO when changing the model the server + client should reset this in conjunction (and without any manual calls to remove model specific data) because we can't know about the internals (which values are synced first e.g.)

**Comment by ThomasMarangoni** [comment]
@Doxoh can you test again?
