### ISSUE TITLE
Add putPlayerInVehicle function

### ISSUE THREAD

**Issue by Michael-xT** [altmp/altv-issues#209]
**Describe the solution you'd like**
I would like to have this function serverside c#.
PutPlayerInVehicle(player (IPlayer), vehicle entity, seatid);
Thanks!

**Comment by rsxdalv** [comment]
What does this function do if the vehicle is outside the streaming range, does it teleport them no matter how far?
What about occupants being there already?

**Comment by AteshM** [comment]
Well, about occupats it should check if thats possible, if it is it will just work, otherwise it should log in console information about command used and seat id. 
About that streaming range, it should work. I want this function just for the spawning car, for example at a job i would like to spawn a car and then insert the player into it. Thats it.

**Comment by OskarSniper** [comment]
You could use the native `0xF75B0D629E1C063D` [setPedIntoVehicle](https://docs.alt-mp.com/#/docs/ClientAPI/modules/natives/ped/setPedIntoVehicle) to achieve this kind of action. Before putting the player into the vehicle check if the seat is free with `0x22AC59A870E6A669` [isVehicleSeatFree](https://docs.alt-mp.com/#/docs/ClientAPI/modules/natives/vehicle/isVehicleSeatFree). Wrap this around a client-side function and call it from your server :)

**Comment by martonp96** [comment]
done
