### ISSUE TITLE
Add possibility to hide or move the watermark

### ISSUE THREAD

**Issue by je-schindler** [altmp/altv-issues#307]
**Is your feature request related to a problem? Please describe.**
I've found out that the watermark is overlaying instructional buttons. This is very ugly.

**Describe the solution you'd like**
It would be nice, if there was a way to hide the watermark.

**Describe alternatives you've considered**
An alternative would be moving the watermark to a better position, adding a possibilty to let developers move the watermark to a position which fits best for them or hiding it only if instructional buttons are shown.

**Additional context**
Screenshot for better understanding:
![problem](https://user-images.githubusercontent.com/14254198/66691361-13073600-ec96-11e9-8f33-51659525265d.png)

**Comment by FabianTerhorst** [comment]
Instead of hiding it maybe try to replace it with altv logo and add a setting for server owners to define the position with left, top, right, bottom, bottom-center, top-center.

**Comment by je-schindler** [comment]
> Instead of hiding it maybe try to replace it with altv logo and add a setting for server owners to define the position with left, top, right, bottom, bottom-center, top-center.

Another alternative.

**Comment by Stolzenberg** [comment]
In my opinion it is not fair to be able to hide it. We are using this mod, so it should be displayed somwhere. 
I like Fabian's idea, but I'd suggest a combination. You can choose between logo (colored and black' 'n white) or text branding and its position on the screen.

**Comment by yoranjj** [comment]
> In my opinion it is not fair to be able to hide it. We are using this mod, so it should be displayed somwhere.
> I like Fabian's idea, but I'd suggest a combination. You can choose between logo (colored and black' 'n white) or text branding and its position on the screen.

I agree, the watermark should stay but it should be able to be moved to different corners of the screen.

**Comment by je-schindler** [comment]
@Stolzenberg If it's fair enough or not depends on the alt:v developers opinion and will be only their decision. But if I think about other multiplayer mods, there was no petmanent watermark (except GTA:Network).
I've just found out, that dispaying it permanently at one static position is not the best.

**Comment by FabianTerhorst** [comment]
I can tell you there are more mods using a none removable watermark. And i think thats the best way to do.

**Comment by Matspyder51** [comment]
Some others mods take you 5$ each month just to change watermark icon 😂 
Maybe right top by default is a better place since no HUD element is at that position, could be great for example to add console command to hide it clientside only, and resetted at every start, that will allow to record some trailers ... without the watermark

**Comment by derRAV3N** [comment]
Hey, I just wanted to chime in on this.

While I think watermarking final products is kinda ugly, in this case I think it's okay to promote alt:V in streams and screenshots. It could also be discussed to just be removed later on when alt:V is more popular and people in the scene know it.

But in the end for now I'd like to have an option to move the watermark to other places, since the current location is quite the spot you'd usually put UI things first, like a smartphone UI, speedometer, interactions, etc.
Also, just as an additional plus point: If we are able to move the watermark to not interfere with a server's UI, it will be more attractive for developers to choose alt:V since they have options and also it will look better to the users.

I'd propose two options for this:

1. Predefine several locations, e.g. every screen corner, centered on any screen edge, corners left or above the minimap, then just provide a function for us to move the watermark to those places.

2. Provide an function for us to give an top/bottom offset and left/right offset and the watermark will then be placed on that spot.

While the 2nd option is more customizable, some things would not be able to be done, like relative positioning for the screen layout, and also there's the "danger" of being able to position the watermark out of screen view, effectively hiding the watermark.
I'd fine with just the first options and I think it's not that much work, AFAIK the watermark is just a webview, so for each predefined position there could a css class which gets applied when the function is called?

**Comment by je-schindler** [comment]
Any updates on this?

**Comment by FabianTerhorst** [comment]
@je-schindler there will be updates on this after merge.

**Comment by zziger** [comment]
Something new about this?

**Comment by tomasvvv** [comment]
watermark takes up an important space now, please make it optional or let server developers change the position of it.

**Comment by martonp96** [comment]
added alt.setWatermarkPosition client function in rc/6.0-rc14
