### ISSUE TITLE
There are 3 natives: setNotificationTextEntry, setNotificationMessage4, drawNotification4 is not Work

### ISSUE THREAD

**Issue by DerKieler91** [altmp/altv-issues#606]
**Client/server version**

`Build #1278, branch rc`

**Current behavior**
Error and no Loading the Gamemode without setNotificationTextEntry, setNotificationMessage4, drawNotification4

**Expected behavior**

There are 3 natives: setNotificationTextEntry, setNotificationMessage4, drawNotification4 is not Work

**Comment by LeonMrBonnie** [comment]
Those natives were deprecated before, and all the deprecated natives just got removed. So this is intended.

**Comment by Lhoerion** [comment]
`setNotificationTextEntry` -> `beginTextCommandThefeedPost`
`setNotificationMessage4` -> `endTextCommandThefeedPostMessagetext`
`drawNotification4` -> `endTextCommandThefeedPostMpticker`

Issue closed because of the specified reasons.
Feel free to respond back here, if you think that it should be reopened.
