### ISSUE TITLE
Event explosion cancellation does nothing

### ISSUE THREAD

**Issue by MacieGx** [altmp/altv-issues#675]
**Client/server version**
2.1-dev4

**Current behavior**
Event explosion cancellation does do nothing
![image](https://user-images.githubusercontent.com/32741786/97236028-7c47e180-17e4-11eb-8eae-f2c694899cbb.png)
![image](https://user-images.githubusercontent.com/32741786/97236034-7fdb6880-17e4-11eb-92db-e265e25ea281.png)

**Expected behavior**
Event explosion should cancel explosion

**Steps to reproduce**
Server:
```
alt.on("explosion", (source, type) => {
  console.log(source, type);
  return false;
});
```
Client:
``game.networkExplodeVehicle(alt.Player.local.vehicle.scriptID, true, true, true);``

**Comment by C0kkie** [comment]
Can confirm it, its also not working in the current stable

**Comment by martonp96** [comment]
The event cancellation works, but the vehicle damage get's synced (also the fire is caused by the fire event, not the explosion event).
If you want to cancel the damage dealt on the vehicle, you have to repair it (works with the newly added vehicle.repair method).
If you want to cancel explosion damage on the players, you have to both cancel the explosion and the weapon damage event.
