### ISSUE TITLE
Screenshot API

### ISSUE THREAD

**Issue by PatrickG** [altmp/altv-issues#80]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the ability to take a screenshot from the GTA window.

**Describe the solution you'd like**
I would suggest adding a `createScreenshot();` function to the `alt` module which returns the screenshot as a base64 encoded string directly or as a promise.

Usage:
```ts
import alt from 'alt';

const webView = new alt.WebView('...');

// Create a screenshot and send it to the WebView:
webView.on('takeScreenshot', () => {
  webView.emit('screenshot', alt.createScreenshot());
});

// Or if `createScreenshot();` returns a promise:
webView.on('takeScreenshot', async () => {
  webView.emit('screenshot', await alt.createScreenshot());
});
```

**Comment by FabianTerhorst** [comment]
This will only be added with a prompt to the user if the user allows or always allows the server to capture the screen.

**Comment by derRAV3N** [comment]
I still don't really understand why the feature will be held back until a permission system is implemented, because the player joined the server on purpose, all the data that the client sees, is managed by the server, there is no way there could be something screenshotted that the server wouldn't be able to get by doing it with code.

**Comment by FabianTerhorst** [comment]
Is implemented already.
