### ISSUE TITLE
Extend alt.takeScreenshot

### ISSUE THREAD

**Issue by Expl1it** [altmp/altv-issues#830]
**Suggestion**
To be able to see cheat (directX hooked) menus with alt.takeScreenshot

**Use cases**
Detect cheaters

**Describe the solution you'd like**
Make a screenshot of the complete directx window?

**Describe alternatives you've considered**
-/-

**Additional context**
-/-

**Comment by FabianTerhorst** [comment]
This would be a privacy problem so it most likely won't be added.

**Comment by zziger** [comment]
If server actually can't screenshot anything but a game and it's own cef gui, then what's the reason for a "Screen Capture" permission? Wouldn't it make more sense if screenshoting game would work without permission, but screenshoting full directx window wouldn't?

**Comment by EtzBetz** [comment]
> If server actually can't screenshot anything but a game and it's own cef gui, then what's the reason for a "Screen Capture" permission?

The reasoning was, that eventually external websites could be opened in CEF and then the contents can be screenshotted, but I didn't see this as a valid reason, but just as well couldn't bring them off of this reasoning.


I thought about maybe adding another permission to also allow DirectX capturing, but the hacker could just disallow it and also it's probably irritating to the user to have to permissions for screenshotting, of which one extends to DirectX context. The only way I see this is generally allowing screenshots without permissions and then adding a permission for DirectX context. But everyone in the dev team is too scared about privacy issues with this, so good luck with arguing.

**Comment by jovanivanovic** [comment]
Adding the whole DirectX context would also screenshot other app overlays such as Discord, Steam and others.

**Comment by EtzBetz** [comment]
Wouldn't it be a measure to have two different permissions for taking screenshots, one is like the one we currently have and another one will take a screenshot with overlays like described here. with this 2nd permission you show an additional warning before youre accepting it, explaining that it could capture private conversations etc. from overlays?

If thats not enough, you could show a short small hint popup in game, when such screenshots are made. but they should displayed at the moment the screenshot is made, or, like, one frame after, so that a potential hacker cant just disable an overlay. at max you could display a hint beforehand the first time this function is used in a session.
