### ISSUE TITLE
Add radio effect to Voice class

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#984]
**Suggestion**
When players speaks together in 3D space and at the same time a person speaks in the radio, it's unrealistic and a little bit difficult to recognize which voices from radio or 3D space.

**Use cases**
Add radio effect when players are in 1D voice communication.

**Describe the solution you'd like**
If it's determined from the server side that a particular 1D voice channel has radio sound effect, on the client side the radio effect is applied to player's microphone and sent to the server.
```js
let channel = new alt.VoiceChannel(false, 1.0);
channel.addRadioEffect();
channel.removeRadioEffect();
```

**Comment by zziger** [comment]
I would go for effects in general, it would be nice to have some way to transform sound stream

**Comment by Tekks** [comment]
_Collection of ideas_

IAudioEffect
* Pitch
* Muffling
* Noise(Radio)
* Echo
* Reverb

```js
let channel = new alt.VoiceChannel(false, 1.0);
let effect = new IAudioEffect.<Effect>(args...)
channel.addEffect(effect);
channel.removeEffect(effect);
```
Maybe direct "attached" to Player.

**Comment by pixlcrashr** [comment]
> _Collection of ideas_
> 
> IAudioEffect
> 
> * Pitch
> * Muffling
> * Noise(Radio)
> * Delay
> * Reverb
> 
> ```js
> let channel = new alt.VoiceChannel(false, 1.0);
> let effect = new IAudioEffect.<Effect>(args...)
> channel.addEffect(effect);
> channel.removeEffect(effect);
> ```
> 
> Maybe direct "attached" to Player.

To extend the above idea:

First, adding audio effects on serverside would, from my understanding of the voice server-system, require to add a static set of predefined voice effects - which would deny adding custom sound effects (e.g. modifying the binary stream data received by a client).

To not only reduce the available audio effects to the ones named above, we instead should only add a general interface, let's say `IVoiceStreamModifier` which is defined as follows:

```ts
export interface IVoiceStreamModifier {
    modify(streamInput: Uint8Array, packetPlayTime: number): Uint8Array;
}
```

This interface then can be added on clientside directly to a specific player (that is non-local) and voice channel.
This means, the following methods have to be added to the `Player` class.

```ts
export class Player {
    ...
    /*
     * @returns The unique id of that specific added stream modifier used to remove it again.
     * @remarks Note, that the voice stream modifier should be stacked (more below).
     */
    addVoiceStreamModifier(voiceChannel: VoiceChannel, modifier: IVoiceStreamModifier): number;
    removeVoiceStreamModifier(voiceChannel: VoiceChannel, uid: number): void;
    ...
}
```

Also note, that this would require the voice channels being synced to players.
Therefore, either the `Voice` class or the `Player` class has to be modified and a new type `VoiceChannel` has to be added:

```ts
export class VoiceChannel {
    // Maybe add an id that can be referred to. Idk, if that already exists internally
    id: number;
    isSpatial: boolean;
    maxDistance: number;
}
```

```
export class Voice {
    ...
    allVoiceChannels: VoiceChannel[];
    ...
}
```

```ts
export class Player {
    ...
    // Voice channels the player currently is in; visible also to every other player
    voiceChannels: VoiceChannel[];
    ...
}
```

When a voice channel was removed on the server, then all locally linked voice stream modifiers will be removed on the clients, too.

The voice stream modifiers are stackable, which means that multiple modifiers can be overdub each other - which may or may not produce strange effects but is intended.

Note that this stream modification system would be more advanced to use due to the necessary requirement of using math to modify the stream, generally.

If I missed something or if you have remarks, go ahead!

**Comment by mrgharabaghi** [comment]
Another useful sound effect could be megaphone for police cars.

**Comment by martonp96** [comment]
Now we have an open source way to add such effects, see:
https://github.com/altmp/voice-filters
